// Static list of all 114 surahs. Keeps the home/reader instant without an API call.
// Source: standard mushaf metadata.
export interface SurahMeta {
  number: number;
  name: string;          // English name
  arabic: string;        // Arabic name
  englishTrans: string;  // Translation of name
  verses: number;
  revelation: "Meccan" | "Medinan";
}

export const SURAHS: SurahMeta[] = [
  { number: 1, name: "Al-Fatihah", arabic: "الفاتحة", englishTrans: "The Opening", verses: 7, revelation: "Meccan" },
  { number: 2, name: "Al-Baqarah", arabic: "البقرة", englishTrans: "The Cow", verses: 286, revelation: "Medinan" },
  { number: 3, name: "Ali 'Imran", arabic: "آل عمران", englishTrans: "Family of Imran", verses: 200, revelation: "Medinan" },
  { number: 4, name: "An-Nisa", arabic: "النساء", englishTrans: "The Women", verses: 176, revelation: "Medinan" },
  { number: 5, name: "Al-Ma'idah", arabic: "المائدة", englishTrans: "The Table Spread", verses: 120, revelation: "Medinan" },
  { number: 6, name: "Al-An'am", arabic: "الأنعام", englishTrans: "The Cattle", verses: 165, revelation: "Meccan" },
  { number: 7, name: "Al-A'raf", arabic: "الأعراف", englishTrans: "The Heights", verses: 206, revelation: "Meccan" },
  { number: 8, name: "Al-Anfal", arabic: "الأنفال", englishTrans: "The Spoils of War", verses: 75, revelation: "Medinan" },
  { number: 9, name: "At-Tawbah", arabic: "التوبة", englishTrans: "The Repentance", verses: 129, revelation: "Medinan" },
  { number: 10, name: "Yunus", arabic: "يونس", englishTrans: "Jonah", verses: 109, revelation: "Meccan" },
  { number: 11, name: "Hud", arabic: "هود", englishTrans: "Hud", verses: 123, revelation: "Meccan" },
  { number: 12, name: "Yusuf", arabic: "يوسف", englishTrans: "Joseph", verses: 111, revelation: "Meccan" },
  { number: 13, name: "Ar-Ra'd", arabic: "الرعد", englishTrans: "The Thunder", verses: 43, revelation: "Medinan" },
  { number: 14, name: "Ibrahim", arabic: "إبراهيم", englishTrans: "Abraham", verses: 52, revelation: "Meccan" },
  { number: 15, name: "Al-Hijr", arabic: "الحجر", englishTrans: "The Rocky Tract", verses: 99, revelation: "Meccan" },
  { number: 16, name: "An-Nahl", arabic: "النحل", englishTrans: "The Bee", verses: 128, revelation: "Meccan" },
  { number: 17, name: "Al-Isra", arabic: "الإسراء", englishTrans: "The Night Journey", verses: 111, revelation: "Meccan" },
  { number: 18, name: "Al-Kahf", arabic: "الكهف", englishTrans: "The Cave", verses: 110, revelation: "Meccan" },
  { number: 19, name: "Maryam", arabic: "مريم", englishTrans: "Mary", verses: 98, revelation: "Meccan" },
  { number: 20, name: "Taha", arabic: "طه", englishTrans: "Ta-Ha", verses: 135, revelation: "Meccan" },
  { number: 21, name: "Al-Anbiya", arabic: "الأنبياء", englishTrans: "The Prophets", verses: 112, revelation: "Meccan" },
  { number: 22, name: "Al-Hajj", arabic: "الحج", englishTrans: "The Pilgrimage", verses: 78, revelation: "Medinan" },
  { number: 23, name: "Al-Mu'minun", arabic: "المؤمنون", englishTrans: "The Believers", verses: 118, revelation: "Meccan" },
  { number: 24, name: "An-Nur", arabic: "النور", englishTrans: "The Light", verses: 64, revelation: "Medinan" },
  { number: 25, name: "Al-Furqan", arabic: "الفرقان", englishTrans: "The Criterion", verses: 77, revelation: "Meccan" },
  { number: 26, name: "Ash-Shu'ara", arabic: "الشعراء", englishTrans: "The Poets", verses: 227, revelation: "Meccan" },
  { number: 27, name: "An-Naml", arabic: "النمل", englishTrans: "The Ant", verses: 93, revelation: "Meccan" },
  { number: 28, name: "Al-Qasas", arabic: "القصص", englishTrans: "The Stories", verses: 88, revelation: "Meccan" },
  { number: 29, name: "Al-'Ankabut", arabic: "العنكبوت", englishTrans: "The Spider", verses: 69, revelation: "Meccan" },
  { number: 30, name: "Ar-Rum", arabic: "الروم", englishTrans: "The Romans", verses: 60, revelation: "Meccan" },
  { number: 31, name: "Luqman", arabic: "لقمان", englishTrans: "Luqman", verses: 34, revelation: "Meccan" },
  { number: 32, name: "As-Sajdah", arabic: "السجدة", englishTrans: "The Prostration", verses: 30, revelation: "Meccan" },
  { number: 33, name: "Al-Ahzab", arabic: "الأحزاب", englishTrans: "The Confederates", verses: 73, revelation: "Medinan" },
  { number: 34, name: "Saba", arabic: "سبأ", englishTrans: "Sheba", verses: 54, revelation: "Meccan" },
  { number: 35, name: "Fatir", arabic: "فاطر", englishTrans: "Originator", verses: 45, revelation: "Meccan" },
  { number: 36, name: "Ya-Sin", arabic: "يس", englishTrans: "Ya-Sin", verses: 83, revelation: "Meccan" },
  { number: 37, name: "As-Saffat", arabic: "الصافات", englishTrans: "Those Ranged in Ranks", verses: 182, revelation: "Meccan" },
  { number: 38, name: "Sad", arabic: "ص", englishTrans: "Sad", verses: 88, revelation: "Meccan" },
  { number: 39, name: "Az-Zumar", arabic: "الزمر", englishTrans: "The Groups", verses: 75, revelation: "Meccan" },
  { number: 40, name: "Ghafir", arabic: "غافر", englishTrans: "The Forgiver", verses: 85, revelation: "Meccan" },
  { number: 41, name: "Fussilat", arabic: "فصلت", englishTrans: "Explained in Detail", verses: 54, revelation: "Meccan" },
  { number: 42, name: "Ash-Shura", arabic: "الشورى", englishTrans: "Consultation", verses: 53, revelation: "Meccan" },
  { number: 43, name: "Az-Zukhruf", arabic: "الزخرف", englishTrans: "Ornaments of Gold", verses: 89, revelation: "Meccan" },
  { number: 44, name: "Ad-Dukhan", arabic: "الدخان", englishTrans: "The Smoke", verses: 59, revelation: "Meccan" },
  { number: 45, name: "Al-Jathiyah", arabic: "الجاثية", englishTrans: "The Kneeling", verses: 37, revelation: "Meccan" },
  { number: 46, name: "Al-Ahqaf", arabic: "الأحقاف", englishTrans: "The Wind-Curved Sandhills", verses: 35, revelation: "Meccan" },
  { number: 47, name: "Muhammad", arabic: "محمد", englishTrans: "Muhammad", verses: 38, revelation: "Medinan" },
  { number: 48, name: "Al-Fath", arabic: "الفتح", englishTrans: "The Victory", verses: 29, revelation: "Medinan" },
  { number: 49, name: "Al-Hujurat", arabic: "الحجرات", englishTrans: "The Rooms", verses: 18, revelation: "Medinan" },
  { number: 50, name: "Qaf", arabic: "ق", englishTrans: "Qaf", verses: 45, revelation: "Meccan" },
  { number: 51, name: "Adh-Dhariyat", arabic: "الذاريات", englishTrans: "The Winnowing Winds", verses: 60, revelation: "Meccan" },
  { number: 52, name: "At-Tur", arabic: "الطور", englishTrans: "The Mount", verses: 49, revelation: "Meccan" },
  { number: 53, name: "An-Najm", arabic: "النجم", englishTrans: "The Star", verses: 62, revelation: "Meccan" },
  { number: 54, name: "Al-Qamar", arabic: "القمر", englishTrans: "The Moon", verses: 55, revelation: "Meccan" },
  { number: 55, name: "Ar-Rahman", arabic: "الرحمن", englishTrans: "The Most Merciful", verses: 78, revelation: "Medinan" },
  { number: 56, name: "Al-Waqi'ah", arabic: "الواقعة", englishTrans: "The Inevitable", verses: 96, revelation: "Meccan" },
  { number: 57, name: "Al-Hadid", arabic: "الحديد", englishTrans: "The Iron", verses: 29, revelation: "Medinan" },
  { number: 58, name: "Al-Mujadilah", arabic: "المجادلة", englishTrans: "The Pleading Woman", verses: 22, revelation: "Medinan" },
  { number: 59, name: "Al-Hashr", arabic: "الحشر", englishTrans: "The Exile", verses: 24, revelation: "Medinan" },
  { number: 60, name: "Al-Mumtahanah", arabic: "الممتحنة", englishTrans: "She That Is To Be Examined", verses: 13, revelation: "Medinan" },
  { number: 61, name: "As-Saff", arabic: "الصف", englishTrans: "The Ranks", verses: 14, revelation: "Medinan" },
  { number: 62, name: "Al-Jumu'ah", arabic: "الجمعة", englishTrans: "Friday", verses: 11, revelation: "Medinan" },
  { number: 63, name: "Al-Munafiqun", arabic: "المنافقون", englishTrans: "The Hypocrites", verses: 11, revelation: "Medinan" },
  { number: 64, name: "At-Taghabun", arabic: "التغابن", englishTrans: "Mutual Disillusion", verses: 18, revelation: "Medinan" },
  { number: 65, name: "At-Talaq", arabic: "الطلاق", englishTrans: "Divorce", verses: 12, revelation: "Medinan" },
  { number: 66, name: "At-Tahrim", arabic: "التحريم", englishTrans: "The Prohibition", verses: 12, revelation: "Medinan" },
  { number: 67, name: "Al-Mulk", arabic: "الملك", englishTrans: "The Sovereignty", verses: 30, revelation: "Meccan" },
  { number: 68, name: "Al-Qalam", arabic: "القلم", englishTrans: "The Pen", verses: 52, revelation: "Meccan" },
  { number: 69, name: "Al-Haqqah", arabic: "الحاقة", englishTrans: "The Reality", verses: 52, revelation: "Meccan" },
  { number: 70, name: "Al-Ma'arij", arabic: "المعارج", englishTrans: "The Ascending Stairways", verses: 44, revelation: "Meccan" },
  { number: 71, name: "Nuh", arabic: "نوح", englishTrans: "Noah", verses: 28, revelation: "Meccan" },
  { number: 72, name: "Al-Jinn", arabic: "الجن", englishTrans: "The Jinn", verses: 28, revelation: "Meccan" },
  { number: 73, name: "Al-Muzzammil", arabic: "المزمل", englishTrans: "The Enshrouded One", verses: 20, revelation: "Meccan" },
  { number: 74, name: "Al-Muddaththir", arabic: "المدثر", englishTrans: "The Cloaked One", verses: 56, revelation: "Meccan" },
  { number: 75, name: "Al-Qiyamah", arabic: "القيامة", englishTrans: "The Resurrection", verses: 40, revelation: "Meccan" },
  { number: 76, name: "Al-Insan", arabic: "الإنسان", englishTrans: "Man", verses: 31, revelation: "Medinan" },
  { number: 77, name: "Al-Mursalat", arabic: "المرسلات", englishTrans: "The Emissaries", verses: 50, revelation: "Meccan" },
  { number: 78, name: "An-Naba", arabic: "النبأ", englishTrans: "The Tidings", verses: 40, revelation: "Meccan" },
  { number: 79, name: "An-Nazi'at", arabic: "النازعات", englishTrans: "Those Who Drag Forth", verses: 46, revelation: "Meccan" },
  { number: 80, name: "'Abasa", arabic: "عبس", englishTrans: "He Frowned", verses: 42, revelation: "Meccan" },
  { number: 81, name: "At-Takwir", arabic: "التكوير", englishTrans: "The Overthrowing", verses: 29, revelation: "Meccan" },
  { number: 82, name: "Al-Infitar", arabic: "الإنفطار", englishTrans: "The Cleaving", verses: 19, revelation: "Meccan" },
  { number: 83, name: "Al-Mutaffifin", arabic: "المطففين", englishTrans: "Defrauding", verses: 36, revelation: "Meccan" },
  { number: 84, name: "Al-Inshiqaq", arabic: "الإنشقاق", englishTrans: "The Splitting Open", verses: 25, revelation: "Meccan" },
  { number: 85, name: "Al-Buruj", arabic: "البروج", englishTrans: "The Mansions of the Stars", verses: 22, revelation: "Meccan" },
  { number: 86, name: "At-Tariq", arabic: "الطارق", englishTrans: "The Morning Star", verses: 17, revelation: "Meccan" },
  { number: 87, name: "Al-A'la", arabic: "الأعلى", englishTrans: "The Most High", verses: 19, revelation: "Meccan" },
  { number: 88, name: "Al-Ghashiyah", arabic: "الغاشية", englishTrans: "The Overwhelming", verses: 26, revelation: "Meccan" },
  { number: 89, name: "Al-Fajr", arabic: "الفجر", englishTrans: "The Dawn", verses: 30, revelation: "Meccan" },
  { number: 90, name: "Al-Balad", arabic: "البلد", englishTrans: "The City", verses: 20, revelation: "Meccan" },
  { number: 91, name: "Ash-Shams", arabic: "الشمس", englishTrans: "The Sun", verses: 15, revelation: "Meccan" },
  { number: 92, name: "Al-Layl", arabic: "الليل", englishTrans: "The Night", verses: 21, revelation: "Meccan" },
  { number: 93, name: "Ad-Duha", arabic: "الضحى", englishTrans: "The Morning Hours", verses: 11, revelation: "Meccan" },
  { number: 94, name: "Ash-Sharh", arabic: "الشرح", englishTrans: "The Relief", verses: 8, revelation: "Meccan" },
  { number: 95, name: "At-Tin", arabic: "التين", englishTrans: "The Fig", verses: 8, revelation: "Meccan" },
  { number: 96, name: "Al-'Alaq", arabic: "العلق", englishTrans: "The Clot", verses: 19, revelation: "Meccan" },
  { number: 97, name: "Al-Qadr", arabic: "القدر", englishTrans: "The Power", verses: 5, revelation: "Meccan" },
  { number: 98, name: "Al-Bayyinah", arabic: "البينة", englishTrans: "The Clear Proof", verses: 8, revelation: "Medinan" },
  { number: 99, name: "Az-Zalzalah", arabic: "الزلزلة", englishTrans: "The Earthquake", verses: 8, revelation: "Medinan" },
  { number: 100, name: "Al-'Adiyat", arabic: "العاديات", englishTrans: "The Courser", verses: 11, revelation: "Meccan" },
  { number: 101, name: "Al-Qari'ah", arabic: "القارعة", englishTrans: "The Calamity", verses: 11, revelation: "Meccan" },
  { number: 102, name: "At-Takathur", arabic: "التكاثر", englishTrans: "Competition", verses: 8, revelation: "Meccan" },
  { number: 103, name: "Al-'Asr", arabic: "العصر", englishTrans: "The Declining Day", verses: 3, revelation: "Meccan" },
  { number: 104, name: "Al-Humazah", arabic: "الهمزة", englishTrans: "The Traducer", verses: 9, revelation: "Meccan" },
  { number: 105, name: "Al-Fil", arabic: "الفيل", englishTrans: "The Elephant", verses: 5, revelation: "Meccan" },
  { number: 106, name: "Quraysh", arabic: "قريش", englishTrans: "Quraysh", verses: 4, revelation: "Meccan" },
  { number: 107, name: "Al-Ma'un", arabic: "الماعون", englishTrans: "Almsgiving", verses: 7, revelation: "Meccan" },
  { number: 108, name: "Al-Kawthar", arabic: "الكوثر", englishTrans: "Abundance", verses: 3, revelation: "Meccan" },
  { number: 109, name: "Al-Kafirun", arabic: "الكافرون", englishTrans: "The Disbelievers", verses: 6, revelation: "Meccan" },
  { number: 110, name: "An-Nasr", arabic: "النصر", englishTrans: "Divine Support", verses: 3, revelation: "Medinan" },
  { number: 111, name: "Al-Masad", arabic: "المسد", englishTrans: "The Palm Fiber", verses: 5, revelation: "Meccan" },
  { number: 112, name: "Al-Ikhlas", arabic: "الإخلاص", englishTrans: "Sincerity", verses: 4, revelation: "Meccan" },
  { number: 113, name: "Al-Falaq", arabic: "الفلق", englishTrans: "The Daybreak", verses: 5, revelation: "Meccan" },
  { number: 114, name: "An-Nas", arabic: "الناس", englishTrans: "Mankind", verses: 6, revelation: "Meccan" },
];

export const TOTAL_VERSES = SURAHS.reduce((sum, s) => sum + s.verses, 0); // 6236

export function getSurah(n: number): SurahMeta | undefined {
  return SURAHS.find((s) => s.number === n);
}
