/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReadRouteImport } from './routes/read'
import { Route as MemorizeRouteImport } from './routes/memorize'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadIndexRouteImport } from './routes/read.index'
import { Route as MemorizeIndexRouteImport } from './routes/memorize.index'
import { Route as ReadSurahRouteImport } from './routes/read.$surah'
import { Route as MemorizeSetIdRouteImport } from './routes/memorize.$setId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadRoute = ReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorizeRoute = MemorizeRouteImport.update({
  id: '/memorize',
  path: '/memorize',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadIndexRoute = ReadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReadRoute,
} as any)
const MemorizeIndexRoute = MemorizeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemorizeRoute,
} as any)
const ReadSurahRoute = ReadSurahRouteImport.update({
  id: '/$surah',
  path: '/$surah',
  getParentRoute: () => ReadRoute,
} as any)
const MemorizeSetIdRoute = MemorizeSetIdRouteImport.update({
  id: '/$setId',
  path: '/$setId',
  getParentRoute: () => MemorizeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/memorize': typeof MemorizeRouteWithChildren
  '/read': typeof ReadRouteWithChildren
  '/settings': typeof SettingsRoute
  '/memorize/$setId': typeof MemorizeSetIdRoute
  '/read/$surah': typeof ReadSurahRoute
  '/memorize/': typeof MemorizeIndexRoute
  '/read/': typeof ReadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/memorize/$setId': typeof MemorizeSetIdRoute
  '/read/$surah': typeof ReadSurahRoute
  '/memorize': typeof MemorizeIndexRoute
  '/read': typeof ReadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/memorize': typeof MemorizeRouteWithChildren
  '/read': typeof ReadRouteWithChildren
  '/settings': typeof SettingsRoute
  '/memorize/$setId': typeof MemorizeSetIdRoute
  '/read/$surah': typeof ReadSurahRoute
  '/memorize/': typeof MemorizeIndexRoute
  '/read/': typeof ReadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/memorize'
    | '/read'
    | '/settings'
    | '/memorize/$setId'
    | '/read/$surah'
    | '/memorize/'
    | '/read/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/memorize/$setId'
    | '/read/$surah'
    | '/memorize'
    | '/read'
  id:
    | '__root__'
    | '/'
    | '/memorize'
    | '/read'
    | '/settings'
    | '/memorize/$setId'
    | '/read/$surah'
    | '/memorize/'
    | '/read/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MemorizeRoute: typeof MemorizeRouteWithChildren
  ReadRoute: typeof ReadRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read': {
      id: '/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof ReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorize': {
      id: '/memorize'
      path: '/memorize'
      fullPath: '/memorize'
      preLoaderRoute: typeof MemorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/': {
      id: '/read/'
      path: '/'
      fullPath: '/read/'
      preLoaderRoute: typeof ReadIndexRouteImport
      parentRoute: typeof ReadRoute
    }
    '/memorize/': {
      id: '/memorize/'
      path: '/'
      fullPath: '/memorize/'
      preLoaderRoute: typeof MemorizeIndexRouteImport
      parentRoute: typeof MemorizeRoute
    }
    '/read/$surah': {
      id: '/read/$surah'
      path: '/$surah'
      fullPath: '/read/$surah'
      preLoaderRoute: typeof ReadSurahRouteImport
      parentRoute: typeof ReadRoute
    }
    '/memorize/$setId': {
      id: '/memorize/$setId'
      path: '/$setId'
      fullPath: '/memorize/$setId'
      preLoaderRoute: typeof MemorizeSetIdRouteImport
      parentRoute: typeof MemorizeRoute
    }
  }
}

interface MemorizeRouteChildren {
  MemorizeSetIdRoute: typeof MemorizeSetIdRoute
  MemorizeIndexRoute: typeof MemorizeIndexRoute
}

const MemorizeRouteChildren: MemorizeRouteChildren = {
  MemorizeSetIdRoute: MemorizeSetIdRoute,
  MemorizeIndexRoute: MemorizeIndexRoute,
}

const MemorizeRouteWithChildren = MemorizeRoute._addFileChildren(
  MemorizeRouteChildren,
)

interface ReadRouteChildren {
  ReadSurahRoute: typeof ReadSurahRoute
  ReadIndexRoute: typeof ReadIndexRoute
}

const ReadRouteChildren: ReadRouteChildren = {
  ReadSurahRoute: ReadSurahRoute,
  ReadIndexRoute: ReadIndexRoute,
}

const ReadRouteWithChildren = ReadRoute._addFileChildren(ReadRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MemorizeRoute: MemorizeRouteWithChildren,
  ReadRoute: ReadRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
